services:

  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3307:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: studentsdb   # (this is just an example, not intended to be a production configuration
      MYSQL_USER: root
      MYSQL_PASSWORD: pwd@123
      MYSQL_ROOT_PASSWORD: pwd@123
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - internalnet 

  pmappserver:
    container_name: pmappservercontainer
    build: ./server 
    image: pmappserver:v1
    ports:
      - 8081:8080
    expose:
      - 8080
    depends_on:
      - mysqldb
    environment:
      DB_HOST: mysqldb
      DB_PASSWORD: 'pwd@123'
      DB_USER: root
      DB_NAME: studentsdb
      DB_PORT: 3306
      DB_CONNECTION_LIMIT: 10 
      SERVER_PORT: 8080   
      SERVICE_TAGS: prod
      SERVICE_NAME: pmappserverservice  
    networks:
      - internalnet
networks:
  internalnet:
    driver: bridge

