version: '3.8'
services:
  frontend:
    image: pmappfrontend:v1
    container_name: pmappfrontendcontainer 
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - server

  server:
    container_name: pmappservercontainer
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: pmappserver:v1
    environment:
      - DB_HOST:mysqldb
      - DB_USER:admin
      - DB_PASSWORD:pwd@123
      - DB_NAME:studentsdb
      - DB_PORT:3306
      - DB_CONNECTION_LIMIT:10
      - SERVER_PORT:8080
      - SERVICE_TAGS=prod
      - SERVICE_NAME=server
    ports:
      - 8081:8080
    expose:
      - 8080
    depends_on:
      - mysqldb

  mysqldb:
    platform: linux/x86_64
    container_name: pmappmysqlcontainer
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=pwd@123
      - MYSQL_DATABASE=studentsdb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=pwd@123
      - SERVICE_TAGS=prod
      - SERVICE_NAME=mysqldb
    ports:
      - 3307:3306
    expose:
      - 3306
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    networks:
      - internalnet

volumes:
  db_data:
networks:
  internalnet:
    driver: bridge